### ISSUE TITLE
Documentation: execute() method does not exist in query()

### ISSUE THREAD

**Issue by miqmago** [aaronpowell/db.js#104]
In README.md:
```javascript
server.people.query( 'firstName' , 'Aaron' )
      .execute()
      .then( function ( results ) {
          // do something with the results
      } );
```

instead it should be:
```javascript
server.people.query( 'firstName' , 'Aaron' )
      .all()
      .execute()
      .then( function ( results ) {
          // do something with the results
      } );
```

or:
```javascript
server.people.query( 'firstName' , 'Aaron' )
      .filter()
      .execute()
      .then( function ( results ) {
          // do something with the results
      } );
```

**Comment by norbornen** [comment]
+1

**Comment by boynet** [comment]
thanks

**Comment by nise** [comment]
+1

**Comment by brettz9** [comment]
I've addressed this in PR #134 by updating the code to match the heading it was under, "Getting a single object by ID".

**Comment by brettz9** [comment]
FYI, I have also made some changes on my fork to expand on the docs in the README which I plan to prepare into a PR. I am wary of you running into merge conflicts, Aaron, though with my multiple PRs (I am basing them all off of `master`) so it'd be easier for me to retrace my steps to make PRs against your current `master` if you can find some time to merge or address some of the PRs when you have time.

**Comment by brettz9** [comment]
With the PR #134 now being merged, I think this issue can be closed (though I still have a PR coming with some more doc additions).

**Comment by aaronpowell** [comment]
Finally someone fixed this, I was just waiting to see who would send the PR :P

**Comment by brettz9** [comment]
Hehe... I want my gold star :)
