### ISSUE TITLE
The CI failed.

### ISSUE THREAD

**Issue by lygstate** [aaronpowell/db.js#108]

**Comment by aaronpowell** [comment]
Yep, the problem is to do with the SauceLab's integration for running the tests. I haven't had the time (or motivation) to fix the CI build

**Comment by MartijnR** [comment]
It would look very good if they passed! :thumbsup: 

(just trying to motivate you)

**Comment by aaronpowell** [comment]
Haha yeah I know :stuck_out_tongue:. The problem was someone else wrote the SauceLabs integration and I never really _got_ how it worked.

On the plus side it looks like PhantomJS v2 supports IndexedDB so I might see about moving to that instead.

**Comment by MartijnR** [comment]
:)

Yes, PhantomJS2 could be a nice solution. (I am loving using karma with a headless task for Travis and a 'browsers' task to launch the same tests in Chrome/Firefox/Safari/Opera locally.)

**Comment by lygstate** [comment]
I'd like to say, the problem is resolved.
In real browser test always a better option.
