### ISSUE TITLE
The unittests doesn't works in firefox.

### ISSUE THREAD

**Issue by lygstate** [aaronpowell/db.js#114]
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
INFO [launcher]: Starting browser Chrome
INFO [launcher]: Starting browser Firefox
INFO [Chrome 40.0.2214 (Windows 7)]: Connected on socket WAYD_BtBE5RnLtxKs4rj with id 10225041
INFO [Firefox 36.0.0 (Windows 7)]: Connected on socket z9kdQ8ThjC7pVpIds4rk with id 21162204
Firefox 36.0.0 (Windows 7) ERROR
  ConstraintError
  at C:/CI-Cor/kexin/db.js/src/db.js:96
Chrome 40.0.2214 (Windows 7): Executed 41 of 61 SUCCESS (0 secs / 12.271 secs)
Chrome 40.0.2214 (Windows 7): Executed 44 of 61 SUCCESS (0 secs / 12.83 secs)
Firefox 36.0.0 (Windows 7): Executed 54 of 61 ERROR (12.317 secs / 12.124 secs)
Chrome 40.0.2214 (Windows 7): Executed 61 of 61 SUCCESS (16.207 secs / 16.179 secs)
Firefox 36.0.0 (Windows 7): Executed 54 of 61 ERROR (12.317 secs / 12.124 secs)
Firefox 36.0.0 (Windows 7) ERROR
  ConstraintError
  at C:/CI-Cor/kexin/db.js/src/db.js:96
Firefox 36.0.0 (Windows 7): Executed 54 of 61 ERROR (11.873 secs / 11.69 secs)
Chrome 40.0.2214 (Windows 7): Executed 61 of 61 SUCCESS (16.525 secs / 16.503 secs)

**Comment by MartijnR** [comment]
possibly relates to #98

**Comment by brettz9** [comment]
Not getting errors anymore in Firefox, so I think this issue can be closed.

**Comment by aaronpowell** [comment]
I'm not getting any in my testing either
