### ISSUE TITLE
Promise is undefined in IE11

### ISSUE THREAD

**Issue by iischwuerfl** [aaronpowell/db.js#118]
Hi,

i'm using your library and everything worked as expected on Chrome.
But testing the app in IE11, i got the following error:

    Promise is undefined
    at db.open (http://localhost:9000/bower_components/db.js/src/db.js:514:13)

Any ideas how to solve this problem?

**Comment by DiegoCardoso** [comment]
Native Promises are not supported in IE. http://caniuse.com/#search=promise
It should use another solution.

**Comment by aaronpowell** [comment]
Native promise support is coming in the next IE engine, aka Project Spartan - https://status.modern.ie/promiseses6?term=promises

You will need to use a polyfill (there are many out there) just like you would with mobile browsers, safari, etc.
