### ISSUE TITLE
How upgrade version indexeddb?

### ISSUE THREAD

**Issue by MasterJobs** [aaronpowell/db.js#120]
I created a IndexedDB and after some modifications need to update your version of IndexedDB. I applied a new version to open the schema, but nothing happens and the IndexedDB gets the same version. The way I found was to delete and recreate. Is there any way to update the version without having to remove and re-create the schema IndexedDB?

**Comment by aaronpowell** [comment]
Changing the version on the settings you pass in didn't work?

**Comment by MasterJobs** [comment]
I found a solution, and I believe it is an oversight on my part. I was putting the values into the opening of the schema, but when I put the schema version directly on the configuration, started to work...
![captura de tela 2015-04-23 as 00 39 02](https://cloud.githubusercontent.com/assets/12078100/7290206/9a981e6a-e951-11e4-9802-10704d226611.png)

**Comment by aaronpowell** [comment]
The version is part of the schema that you provide. Referring to your screenshot you should uncomment the line below `server: 'test'`.
