### ISSUE TITLE
Unit Tests failing - runs and waitsFor are undefined

### ISSUE THREAD

**Issue by mikemorton** [aaronpowell/db.js#121]
I forked the repo today and tried to get up and running playing with this thing.

I noticed the contribution instructions were not 100% correct.  I had to run `bower` before running `grunt jasmine-server` and that's not in the instructions.  Also the instructions currently say jasmine-**sever** as opposed to **server**.

Anyways, once I worked past those issues I got the tests running and encountered errors in 57/61 specs with the following error in nearly all of them: `runs is not a function`  A bit of googling tells me that these issues are because the tests are [using old jasmine syntax](http://stackoverflow.com/questions/20963038/jasmine-2-0-refactoring-out-1-3s-runs-and-waitsfor).

It seems the repo recently was upgraded to Jasmine 2.2.1 - Maybe some other changes were missed with that?

**Comment by aaronpowell** [comment]
Quite possible that some of the tests haven't been updated. The person who submitted the PR's for them ended up doing a huge refactor with some test changes which I rejected and requested they be split out to smaller PR's (ie - just the test fixes, the feature changes, etc). They told me to do it myself so the PR was rejected.

If you can send a PR that fixes those tests (and adds the missing doco steps) I'd really appreciate it :smile:

**Comment by mikemorton** [comment]
I'm not sure I have the time or the expertise to do that.  If I revert my repository back to 32d7a43ec16576736f91d7d8d58154b0b46814ed all of the tests pass.  Would you consider reverting all of the March 11th changes?  Was there any groundbreaking stuff in there that the code now relies on?

**Comment by mikemorton** [comment]
Yeah it looks like @lygstate updated the db-open test specs in PR #110 but didn't update any of the other specs.  His master branch has updates to the other specs but seems to be a mix of other changes. :/

**Comment by aaronpowell** [comment]
i'd prefer not to revert, the upgrade is useful but I don't have the time at the moment to fix it up :(

**Comment by mikemorton** [comment]
Okay this weekend I'll see if it's trivial to bring over the other test spec changes made by @lygstate.

**Comment by mikemorton** [comment]
Yeah I took a look at copying over his test case changes but they're too tightly coupled with this API changes.

You'll have to either integrate his massive PR, rollback his jasmine upgrade changes or live with the fact that the tests are nearly all failing. :cry:

**Comment by brettz9** [comment]
This has been addressed by c0b022bc45ae1924f7961eaed88f24aa28f1ddc7 and some other commits that correct the README, so this can be closed.
