### ISSUE TITLE
Count all records ?

### ISSUE THREAD

**Issue by nikatlas** [aaronpowell/db.js#124]
How can i get the count of all the records in a table ?

I see there is a count() method on only() as well as on bound() lower/upper Bound()... 

all() method doesn't have one.

What is the fastest way to count a table's records ? 
It should be trivial i suppose...

**Comment by brettz9** [comment]
This can be achieved by `server.count()`.

As far as docs and tests, I've added some in PR #152 .

**Comment by brettz9** [comment]
I think this can be closed now.
