### ISSUE TITLE
Do not use reserved keyword as method names

### ISSUE THREAD

**Issue by hansenfreddy** [aaronpowell/db.js#127]
Background: Using a minification tool that breaks because of db.js use of reserved keywords.

Problems with: delete and continue

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Keywords

Is it possible to find new names?

**Comment by aaronpowell** [comment]
Which minifier is breaking? I haven't had any problems.

Also `continue` is part of the IndexedDB API so I can't not use it :wink:

**Comment by brettz9** [comment]
I think this issue should be closed as you are now uglifying in `dist` output. Also, it is marginally more readable to avoid escaping `delete()` with `['delete']()` (In PR #134 I've undone these particular JSLint-based changes I made earlier), and such escaping is not necessary anymore in ES6 which is what you are using in source...

**Comment by aaronpowell** [comment]
Yep, now I'm putting a minified version in the release there's no need to use your own minifier.
