### ISSUE TITLE
I would love more documentation

### ISSUE THREAD

**Issue by DjebbZ** [aaronpowell/db.js#15]
Hi

Amongst all the project I saw wrapping IndexedDB, yours is the most tested but one of the less documented. It's like using db.js requires a non-trivial knowledge of IndexedDB, plus a knowledge of how to use db.js itself.

An example, as I'm just starting to use it : when using `db.open`, the `server` and `version` are required, but the `schema`. I had the read all the open-db.js spec file to learn how to create a database. Not very cool for a library that tries to simplify the usage of complex API.

But worry not, this comment is not a rant, rather a proposal of help. I'd like to write some public facing docs so that people effectively don't need to read code/specs to use it. Just need approval and some guidance about how you see it.

Sidenote : your project seem to be compatible with the [IndexedDBShim](http://nparashuram.com/IndexedDBShim/), which is pretty cool, and one of the reason I choose to use your project.

**Comment by brettz9** [comment]
I think we can close this issue now since the README has been enhanced to cover the API. There are already issues for Docco generation (issue #21 ) and for porting your blog (issue #19 ).

**Comment by DjebbZ** [comment]
Indeed, README looks complete with regard to usage and API. No interest in db.js now, but closing anyway to keep the issues clean. Thanks for the reminder.
