### ISSUE TITLE
Shorthand for query().all().execute()

### ISSUE THREAD

**Issue by brettz9** [aaronpowell/db.js#150]
Would you be open to allowing for

```js
query().execute();
```

in place of:

```js
query().all().execute();
```

**Comment by brettz9** [comment]
And a `executeQuery()` would be great too... Too long of a chain to have the jQuery-type succinctness and still both proposals are I think semantically clear...

**Comment by aaronpowell** [comment]
I dislike the ambiguity of `query().execute()`. The goal is to keep it clear and expressive.
