### ISSUE TITLE
CHANGES.md file

### ISSUE THREAD

**Issue by brettz9** [aaronpowell/db.js#155]
Whenever you might decide to bump the version, I'd like to request we add a CHANGES.md file so as to provide highlights of past releases.

**Comment by aaronpowell** [comment]
Should do, know of any easy way to automate this, I'm lazy about pulling together pages of documentation.

**Comment by brettz9** [comment]
Do you mean so that the CHANGES.md shows up in tagged release pages? If that's what you mean, there is a discussion about this at https://github.com/olivierlacan/keep-a-changelog/issues/1 , but it doesn't look like any JavaScript-based tools are ready to do this yet.

**Comment by brettz9** [comment]
The CHANGES is just to highlight, in a human-readable way, an overview of what main features, bug fixes, etc. were covered in a given version (for those who don't want to decipher the sometimes overly specific commit messages). I think it would be fine to just start with the current version and add the summary for it and just add to it whenever you decide to publish an update to `npm`. It would be nice to automate also adding this to the Github release pages as mentioned in my last comment, but:

1. A CHANGES.md file alone would be fine, imo, especially if you are tagging the releases.
2. I assume it shouldn't be too hard to paste the latest markdown except into the releases page, especially since releases are not all that frequent.

**Comment by aaronpowell** [comment]
I really need to remember to tag releases. Just realised that I didn't tag 0.12 :grimacing:

**Comment by brettz9** [comment]
I think you can create a new branch locally based on say `master` and then hard reset to the last commit you want, and then push/tag that.

**Comment by aaronpowell** [comment]
yeah I know you can back-tag, it's more working out the commits to back it to :stuck_out_tongue:

**Comment by brettz9** [comment]
How about we add a `CHANGES.md` file for now, and then use [chandler](https://github.com/mattbrictson/chandler) or [chag](https://github.com/mtdowling/chag) (or wait for/write our own Node-based one utilizing a [Markdown parser](https://github.com/chjj/marked) and Github API info on [releases](https://developer.github.com/v3/repos/releases/#edit-a-release) and [tags](https://developer.github.com/v3/git/tags/#create-a-tag-object)).

It is compelling, as discussed in the previously referenced thread as well, to use the CHANGES file as the canonical source of changes, so even without it being added to Github releases/tags, it could be in the future.

**Comment by brettz9** [comment]
I'll close this since got what I wanted, but of course you can reopen or start a new issue if you want to track the idea of having some code parse the CHANGES file and push to the Github API.
