### ISSUE TITLE
Npm Registry

### ISSUE THREAD

**Issue by tomgutz** [aaronpowell/db.js#30]
Hi, this might not be an issue but I would like to ask if there are any plans for this tool to be part of the npm registry.Thanks!

**Comment by darkyen** [comment]
Um @aaronmccall Now it is required. because tons of project and the whole react band-wagon is on npm

**Comment by aaronpowell** [comment]
Yep, now that browserify/webpack are taking off it makes sense.

The latest version is now on npm.

**Comment by darkyen** [comment]
thank you so much, you are our hero !
