### ISSUE TITLE
Limit should return more properties

### ISSUE THREAD

**Issue by TheSavior** [aaronpowell/db.js#57]
I'm not quite sure I understand any implementation reason by looking through the code as to why limit needs to only return execute. I want to do something like:

    server.profiles.query('name')
        .lowerBound('marcy')
        .limit(5)
        .modify({views: function(profile) { return profile.views + 1; }})
        .execute()
        .done(...)

Granted, the above example is pretty silly since it's incrementing profile views, but in combination with the delete request, it's pretty useful as you can then remove 5 items starting at a bound.

**Comment by brettz9** [comment]
FYI, `limit` can be added after `modify` and it will still apply to the modification. However, I do agree it would make sense to allow more methods after `limit` to allow for such an order.

**Comment by brettz9** [comment]
This issue (including the example in the OP) was handled by the `limit` PR, so this can be closed.
