### ISSUE TITLE
Can't run tests because of invalid jade version

### ISSUE THREAD

**Issue by TheSavior** [aaronpowell/db.js#61]
I'm trying to run the test suite, which fails with deprecated errors and syntax errors which appears to be due to the package.json give jade a * version expectation.

I am trying to add a test which seems to demonstrate a failing issue with adding indexes, but there are no instructions on how to get this to run locally and I couldn't get a new account with saucelabs set up and integrated with travis-ci. I'll reference this issue from the one with the failing test.

**Comment by brettz9** [comment]
This has been implemented by c0b022bc45ae1924f7961eaed88f24aa28f1ddc7 so I think this can be closed.

**Comment by aaronpowell** [comment]
There's been some upgrades and it _works on my machine_.
