### ISSUE TITLE
Error in readme code example

### ISSUE THREAD

**Issue by erik-southmedia** [aaronpowell/db.js#80]
In the readme document you have a code example to get a single object by ID:

server.people.query( 'firstName' , 'Aaron' )
      .execute()
      .done( function ( results ) {
          // do something with the results
      } );

However, this doesn't work for me and looking through your test script it seems that this is achieved by the get() function instead of query(). If so, could you please update your readme. Thanks.

**Comment by brettz9** [comment]
I've fixed this in PR #134

**Comment by brettz9** [comment]
With the PR #134 now being merged, I think this issue can be closed.
