### ISSUE TITLE
db.js in conjunction with IndexedDBShim and autoIncrement

### ISSUE THREAD

**Issue by icodeforlove** [aaronpowell/db.js#82]
Basically autoIncrement doesn't work with the shim.

There has been a solution posted here (https://github.com/axemclion/IndexedDBShim/issues/67#issuecomment-50332235).

Not sure if the fix should land in IndexedDBShim or DB.js, but I'm posting this so others can still get them to play together

**Comment by aaronpowell** [comment]
I'm going to close this issue as the problem lies within the shim and I'd prefer not to put code into db.js specifically to patch bugs in the shim (also, with iOS 8 now actually having IDB support the shim is less needed).
