### ISSUE TITLE
update bower package

### ISSUE THREAD

**Issue by MartijnR** [aaronpowell/db.js#96]
Great tool! Would be great if the package could be updated in bower.

**Comment by aaronpowell** [comment]
I thought bower grabbed the latest from GitHub? What is up there?

**Comment by MartijnR** [comment]
Ah is that how it's supposed to work. Just tried fresh install and the package.json shows version 0.0.1. The .bower.json shows 0.9.0.

**Comment by MartijnR** [comment]
Am not familiar but bower, but I wonder if the issue is that the bower version has a .bower.json (note first dot) and not a bower.json in the project root. Maybe bower is looking for changes to a config file that no longer exists?

**Comment by MartijnR** [comment]
My .bower.json comment can be ignored (it's an internal bower thing). 

I believe all that is required to update the lib in bower is to update the git tags. Right now bower installs the version that is more than 1 year old (the commit tagged as 0.9.0 on the 20th of January 2014).

P.S. Maybe it's time for a version update to 0.9.3. too! :)

**Comment by aaronpowell** [comment]
If you can get a PR for #97 I’ll cut a new version with that fix in it ☺

**Comment by MartijnR** [comment]
Deal!

**Comment by GeorgS** [comment]
:+1: yes, please update the bower package

**Comment by aaronpowell** [comment]
Done, latest is now on bwoer

**Comment by MartijnR** [comment]
Is is possible to cut a new version again (new git tag), so it's picked up by bower?.

**Comment by aaronpowell** [comment]
Should be done now. I've also published a new npm package (I don't use bower, I use npm)

**Comment by MartijnR** [comment]
Thanks!
