### ISSUE TITLE
rejection in add() and update() has two parameters

### ISSUE THREAD

**Issue by MartijnR** [aaronpowell/db.js#97]
I'm wondering why add() and update() reject onerror with 2 parameters. Is there a reason for this?

https://github.com/aaronpowell/db.js/blob/master/src/db.js#L111
https://github.com/aaronpowell/db.js/blob/master/src/db.js#L155

I would expect it to reject with:

```reject(e)``` instead of ```reject(records, e)```

**Comment by aaronpowell** [comment]
This is an error, it should be only rejecting with a single argument to be compliant with the ES6 promises.

**Comment by MartijnR** [comment]
same with the 2 onabort handlers

Would like a PR for this?

**Comment by aaronpowell** [comment]
Yep! Everywhere should only have a single argument (resolve and reject). I just haven’t had time to address it yet

**Comment by aaronpowell** [comment]
Merged and on npm + bower as v0.10.0
