### ISSUE TITLE
Firefox throws ConstraintError and aborts hard when key already exists

### ISSUE THREAD

**Issue by MartijnR** [aaronpowell/db.js#98]
Seen in FF 35.0 and the previous version on OS X 10.10.

If an attempt is made to add a record when a record with the same key already exists, FF throws a ConstraintError causing the transaction to abort hard without properly rejecting it.

Other browsers don't have this problem.

I think the issue is described here: https://bugzilla.mozilla.org/show_bug.cgi?id=872873

Adding `e.preventDefault()` to the error handler of the `add` function solves it for me:

```js
transaction.onerror = function ( e ) {
     // prevent Firefox from throwing a ConstraintError and aborting (hard)
     e.preventDefault();
     reject( records , e );
};
```

**Comment by aaronpowell** [comment]
Ahh browser abnormalities. I'll see about getting that added to the codebase when I have a chance.

**Comment by MartijnR** [comment]
Great. Thanks!

**Comment by lygstate** [comment]
Thanks, should be fixed.
