### ISSUE TITLE
Library should not throw immediately if indexedDB cannot be found.

### ISSUE THREAD

**Issue by lukebayes** [aaronpowell/db.js#99]
I'm trying to write tests for features the require this library and IndexedDB does not exist in our test environment (Node with Domino JS).

We can easily swap out our implementation with a fake IndexedDB, but unfortunately, this library throws as soon as it's evaluated.

I'm considering a pull request that would lazily load the global reference to IndexedDB after the first request rather than immediately upon evaluation.

Thoughts?

**Comment by aaronpowell** [comment]
Why wouldn’t you just run your shim before you add the db.js reference to the page?

**Comment by lukebayes** [comment]
Because we're using webpack/browserify as a module loader and the require statements for a given module belong at the top of the file. The dependency check happens at system evaluation. In general, I expect to be able to non-destructively load modules and then provide fakes to my system at any point in time.

Here's an example of the kind of functionality that I'm referring to:

```javascript
var db = require('db');

var Foo = function(opt_providedDB) {
  this._db = providedDB || db;
};
```

In production (in the browser), this might be created like:
```javascript
var foo = new Foo();
```

In test, it would instead be:
```javascript
var foo = new Foo(fakeDb);
```

**Comment by lukebayes** [comment]
Went ahead and created a pull request so it's clear what I'm proposing. This should still provide the expected safety in that it will still throw if IndexedDB cannot be found, but now it happens when code tries to access it, rather than at system evaluation.

**Comment by aaronpowell** [comment]
Sure, I get the use-case with webpack/browserify, but what I'm wondering is why aren't you putting your test shims in _before_ you add your packed JS, it's obviously being added at _some point_ for the tests to run so why not add it before?

**Comment by aaronpowell** [comment]
I'm merged the PR regardless.

**Comment by lukebayes** [comment]
Thanks for the merge!

**Comment by lygstate** [comment]
This should be close?

**Comment by lukebayes** [comment]
Ah - yes. Thanks for the reminder!
